language: node_js
node_js:
  - "node"
install:
  - npm install -g codecov
  - npm ci
after_success:
  - ./bin/slim-cover.js --reporter codecov --destination coverage.json
  - codecov --file=coverage.json