language: node_js
node_js:
  - "node"
install:
  - npm install -g codecov
  - npm ci
script:
  - ./bin/slim-cover.js --include src --reporter terminal --reporter codecov,coverage.json
after_success:
  - codecov --file=coverage.json