language: node_js
node_js:
  - "node"
install:
  - npm ci
  - npm install codecov jasmine
script:
  - ./bin/slim-cover.js --include src --reporter terminal --reporter codecov,coverage.json
after_success:
  - npx codecov --file=coverage.json